// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prova.Data;

#nullable disable

namespace Prova.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20231211062040_NOME_DA_MIGRACAO")]
    partial class NOME_DA_MIGRACAO
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.22");

            modelBuilder.Entity("Prova.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            Nome = "João Silva"
                        },
                        new
                        {
                            ClienteId = 2,
                            Nome = "Maria Oliveira"
                        },
                        new
                        {
                            ClienteId = 3,
                            Nome = "José Santos"
                        });
                });

            modelBuilder.Entity("Prova.Models.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("PedidoId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Pedidos");

                    b.HasData(
                        new
                        {
                            PedidoId = 1,
                            ClienteId = 1,
                            CriadoEm = new DateTime(2023, 12, 12, 3, 20, 40, 697, DateTimeKind.Local).AddTicks(635),
                            Descricao = "Descrição do Pedido 1",
                            Nome = "Pedido 1"
                        },
                        new
                        {
                            PedidoId = 2,
                            ClienteId = 2,
                            CriadoEm = new DateTime(2023, 12, 13, 3, 20, 40, 697, DateTimeKind.Local).AddTicks(645),
                            Descricao = "Descrição do Pedido 2",
                            Nome = "Pedido 2"
                        },
                        new
                        {
                            PedidoId = 3,
                            ClienteId = 3,
                            CriadoEm = new DateTime(2023, 12, 14, 3, 20, 40, 697, DateTimeKind.Local).AddTicks(647),
                            Descricao = "Descrição do Pedido 3",
                            Nome = "Pedido 3"
                        });
                });

            modelBuilder.Entity("Prova.Models.Pedido", b =>
                {
                    b.HasOne("Prova.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
